services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fitness-app
    env_file:
      - .env
    ports:
      - "5001:5000"
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8
    container_name: mysql-fitness
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Oemry241995@
      MYSQL_DATABASE: fitness_booking
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis-fitness
    ports:
      - "6380:6379"

volumes:
  mysql-data:
